name: Release
on:  
  push:    
    branches: [ "main","testlerna" ]
jobs:  
  release:    
    name: Release    
    runs-on: ubuntu-latest    
    steps:      
      - uses: actions/checkout@master      
      - uses: actions/setup-node@v1        
        with:          
          node-version: "14.x"      
      - run: lerna exec --concurrency 1 -- npx semantic-release -e semantic-release-monorepo        
        env:          
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}          